/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete.menu;

import java.awt.Color;
import Paquete.cliente.listado_clientes;
import javax.swing.JFrame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.UIManager;
/**
 *
 * @author oscar
 */
public class princip extends javax.swing.JFrame {

    Color panedefault;
    Color paneClick;
    Color btndefault;
    Color btnClick;
    
    
    public princip() {
        initComponents();
        panedefault = new Color(0,0,0);
        paneClick = new Color(255,255,255);
        btndefault = new Color(102,102,102);
        btnClick = new Color(112,96,97);
        psHome.setBackground(paneClick);
        psClientes.setBackground(panedefault);
        psProductos.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psVentas.setBackground(panedefault);
        usuario.setVisible(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        pnlPrincipal.removeAll();
        menu c=new menu();
        pnlPrincipal.add(c).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnCliente = new javax.swing.JPanel();
        psClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnProducto = new javax.swing.JPanel();
        psProductos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        psHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JPanel();
        psVentas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCompras = new javax.swing.JPanel();
        psCompras = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JPanel();
        psProveedores = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnProveedores1 = new javax.swing.JPanel();
        psProveedores2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnProveedores4 = new javax.swing.JPanel();
        psProveedores5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnProveedores5 = new javax.swing.JPanel();
        psProveedores6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtHome = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(153, 153, 153));

        btnCliente.setBackground(new java.awt.Color(102, 102, 102));
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClienteMousePressed(evt);
            }
        });

        psClientes.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psClientesLayout = new javax.swing.GroupLayout(psClientes);
        psClientes.setLayout(psClientesLayout);
        psClientesLayout.setHorizontalGroup(
            psClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psClientesLayout.setVerticalGroup(
            psClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/imagenes/tab_client_icon-icons.com_72436.png"))); // NOI18N

        javax.swing.GroupLayout btnClienteLayout = new javax.swing.GroupLayout(btnCliente);
        btnCliente.setLayout(btnClienteLayout);
        btnClienteLayout.setHorizontalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClienteLayout.createSequentialGroup()
                .addComponent(psClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnClienteLayout.setVerticalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(psClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        btnProducto.setBackground(new java.awt.Color(102, 102, 102));
        btnProducto.setPreferredSize(new java.awt.Dimension(20, 40));
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductoMousePressed(evt);
            }
        });

        psProductos.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psProductosLayout = new javax.swing.GroupLayout(psProductos);
        psProductos.setLayout(psProductosLayout);
        psProductosLayout.setHorizontalGroup(
            psProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psProductosLayout.setVerticalGroup(
            psProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/imagenes/carga.png"))); // NOI18N

        javax.swing.GroupLayout btnProductoLayout = new javax.swing.GroupLayout(btnProducto);
        btnProducto.setLayout(btnProductoLayout);
        btnProductoLayout.setHorizontalGroup(
            btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductoLayout.createSequentialGroup()
                .addComponent(psProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnProductoLayout.setVerticalGroup(
            btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnHome.setBackground(new java.awt.Color(102, 102, 102));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });

        psHome.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psHomeLayout = new javax.swing.GroupLayout(psHome);
        psHome.setLayout(psHomeLayout);
        psHomeLayout.setHorizontalGroup(
            psHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psHomeLayout.setVerticalGroup(
            psHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/imagenes/casa.png"))); // NOI18N

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(psHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(psHome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        usuario.setText("0");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/imagenes/iconfinder_logout_account_exit_door_3005766.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btnVenta.setBackground(new java.awt.Color(102, 102, 102));
        btnVenta.setPreferredSize(new java.awt.Dimension(20, 40));
        btnVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentaMousePressed(evt);
            }
        });

        psVentas.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psVentasLayout = new javax.swing.GroupLayout(psVentas);
        psVentas.setLayout(psVentasLayout);
        psVentasLayout.setHorizontalGroup(
            psVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psVentasLayout.setVerticalGroup(
            psVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ventas");

        javax.swing.GroupLayout btnVentaLayout = new javax.swing.GroupLayout(btnVenta);
        btnVenta.setLayout(btnVentaLayout);
        btnVentaLayout.setHorizontalGroup(
            btnVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVentaLayout.createSequentialGroup()
                .addComponent(psVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVentaLayout.setVerticalGroup(
            btnVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnCompras.setBackground(new java.awt.Color(102, 102, 102));
        btnCompras.setPreferredSize(new java.awt.Dimension(20, 40));
        btnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComprasMousePressed(evt);
            }
        });

        psCompras.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psComprasLayout = new javax.swing.GroupLayout(psCompras);
        psCompras.setLayout(psComprasLayout);
        psComprasLayout.setHorizontalGroup(
            psComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psComprasLayout.setVerticalGroup(
            psComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Compras");

        javax.swing.GroupLayout btnComprasLayout = new javax.swing.GroupLayout(btnCompras);
        btnCompras.setLayout(btnComprasLayout);
        btnComprasLayout.setHorizontalGroup(
            btnComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComprasLayout.createSequentialGroup()
                .addComponent(psCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnComprasLayout.setVerticalGroup(
            btnComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnProveedores.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedores.setPreferredSize(new java.awt.Dimension(20, 40));
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedoresMousePressed(evt);
            }
        });

        psProveedores.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psProveedoresLayout = new javax.swing.GroupLayout(psProveedores);
        psProveedores.setLayout(psProveedoresLayout);
        psProveedoresLayout.setHorizontalGroup(
            psProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psProveedoresLayout.setVerticalGroup(
            psProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("prove");

        javax.swing.GroupLayout btnProveedoresLayout = new javax.swing.GroupLayout(btnProveedores);
        btnProveedores.setLayout(btnProveedoresLayout);
        btnProveedoresLayout.setHorizontalGroup(
            btnProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProveedoresLayout.createSequentialGroup()
                .addComponent(psProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnProveedoresLayout.setVerticalGroup(
            btnProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnProveedores1.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedores1.setPreferredSize(new java.awt.Dimension(20, 40));
        btnProveedores1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedores1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedores1MousePressed(evt);
            }
        });

        psProveedores2.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psProveedores2Layout = new javax.swing.GroupLayout(psProveedores2);
        psProveedores2.setLayout(psProveedores2Layout);
        psProveedores2Layout.setHorizontalGroup(
            psProveedores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psProveedores2Layout.setVerticalGroup(
            psProveedores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("orden");

        javax.swing.GroupLayout btnProveedores1Layout = new javax.swing.GroupLayout(btnProveedores1);
        btnProveedores1.setLayout(btnProveedores1Layout);
        btnProveedores1Layout.setHorizontalGroup(
            btnProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProveedores1Layout.createSequentialGroup()
                .addComponent(psProveedores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnProveedores1Layout.setVerticalGroup(
            btnProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psProveedores2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnProveedores4.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedores4.setPreferredSize(new java.awt.Dimension(20, 40));
        btnProveedores4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedores4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedores4MousePressed(evt);
            }
        });

        psProveedores5.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psProveedores5Layout = new javax.swing.GroupLayout(psProveedores5);
        psProveedores5.setLayout(psProveedores5Layout);
        psProveedores5Layout.setHorizontalGroup(
            psProveedores5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psProveedores5Layout.setVerticalGroup(
            psProveedores5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Adelanto");

        javax.swing.GroupLayout btnProveedores4Layout = new javax.swing.GroupLayout(btnProveedores4);
        btnProveedores4.setLayout(btnProveedores4Layout);
        btnProveedores4Layout.setHorizontalGroup(
            btnProveedores4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProveedores4Layout.createSequentialGroup()
                .addComponent(psProveedores5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnProveedores4Layout.setVerticalGroup(
            btnProveedores4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psProveedores5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnProveedores5.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedores5.setPreferredSize(new java.awt.Dimension(20, 40));
        btnProveedores5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedores5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedores5MousePressed(evt);
            }
        });

        psProveedores6.setPreferredSize(new java.awt.Dimension(5, 26));

        javax.swing.GroupLayout psProveedores6Layout = new javax.swing.GroupLayout(psProveedores6);
        psProveedores6.setLayout(psProveedores6Layout);
        psProveedores6Layout.setHorizontalGroup(
            psProveedores6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        psProveedores6Layout.setVerticalGroup(
            psProveedores6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Funcionarios");

        javax.swing.GroupLayout btnProveedores5Layout = new javax.swing.GroupLayout(btnProveedores5);
        btnProveedores5.setLayout(btnProveedores5Layout);
        btnProveedores5Layout.setHorizontalGroup(
            btnProveedores5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProveedores5Layout.createSequentialGroup()
                .addComponent(psProveedores6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnProveedores5Layout.setVerticalGroup(
            btnProveedores5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psProveedores6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btnProveedores1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btnProveedores4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btnProveedores5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, 1000));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1774, 1000));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1774, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 970));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        txtHome.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        txtHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHome, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHome, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 80));

        jPanel4.setBackground(new java.awt.Color(220, 207, 175));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1780, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1780, 80));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 989));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1778, 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1778, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        setSize(new java.awt.Dimension(1935, 1070));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        psClientes.setBackground(panedefault);
        psProductos.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psVentas.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        
        psHome.setBackground(paneClick);
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMousePressed
        psHome.setBackground(panedefault);
        psProductos.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psVentas.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        
        psClientes.setBackground(paneClick);
    }//GEN-LAST:event_btnClienteMousePressed

    private void btnProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMousePressed
        psHome.setBackground(panedefault);
        psClientes.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psVentas.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        
        
        psProductos.setBackground(paneClick);
    }//GEN-LAST:event_btnProductoMousePressed

    private void btnProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        productos_lista p=new productos_lista();
        pnlPrincipal.add(p).setVisible(true);
        int width = pnlPrincipal.getWidth();
       int Height = pnlPrincipal.getHeight();
       p.setSize(width, Height);
        
    }//GEN-LAST:event_btnProductoMouseClicked

    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        txtHome.setText("CLIENTES");
        pnlPrincipal.removeAll();
      pnlPrincipal.repaint();
      cliente c=new cliente();
      pnlPrincipal.add(c).setVisible(true);
       int width = pnlPrincipal.getWidth();
       int Height = pnlPrincipal.getHeight();
       c.setSize(width, Height);
    }//GEN-LAST:event_btnClienteMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        txtHome.setText("INICIO");
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        menu c=new menu();
        pnlPrincipal.add(c).setVisible(true);
       int width = pnlPrincipal.getWidth();
       int Height = pnlPrincipal.getHeight();
       c.setSize(width, Height);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaMouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        factura c=new factura();
        pnlPrincipal.add(c).setVisible(true);
       int width = pnlPrincipal.getWidth();
       int Height = pnlPrincipal.getHeight();
       c.setSize(width, Height);
    }//GEN-LAST:event_btnVentaMouseClicked

    private void btnVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaMousePressed
        psClientes.setBackground(panedefault);
        psProductos.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psHome.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        
        psVentas.setBackground(paneClick);
    }//GEN-LAST:event_btnVentaMousePressed

    private void btnComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        compras p=new compras();
        pnlPrincipal.add(p).setVisible(true);
       int width = pnlPrincipal.getWidth();
       int Height = pnlPrincipal.getHeight();
       p.setSize(width, Height);
    }//GEN-LAST:event_btnComprasMouseClicked

    private void btnComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMousePressed
        psClientes.setBackground(panedefault);
        psProductos.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psHome.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        psVentas.setBackground(panedefault);
        
        psCompras.setBackground(paneClick);
    }//GEN-LAST:event_btnComprasMousePressed

    private void btnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        proveedores p=new proveedores();
        pnlPrincipal.add(p).setVisible(true);
       int width = pnlPrincipal.getWidth();
       int Height = pnlPrincipal.getHeight();
       p.setSize(width, Height);
        
    }//GEN-LAST:event_btnProveedoresMouseClicked

    private void btnProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMousePressed
        psClientes.setBackground(panedefault);
        psProductos.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        psHome.setBackground(panedefault);
        psProveedores.setBackground(panedefault);
        psVentas.setBackground(panedefault);
        psCompras.setBackground(panedefault);
        
        psProveedores.setBackground(paneClick);
    }//GEN-LAST:event_btnProveedoresMousePressed

    private void btnProveedores1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedores1MouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        orden p=new orden();
        pnlPrincipal.add(p).setVisible(true);
        int width = pnlPrincipal.getWidth();
        int Height = pnlPrincipal.getHeight();
        p.setSize(width, Height);
    }//GEN-LAST:event_btnProveedores1MouseClicked

    private void btnProveedores1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedores1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedores1MousePressed

    private void btnProveedores4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedores4MouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        adelantos p=new adelantos();
        pnlPrincipal.add(p).setVisible(true);
        int width = pnlPrincipal.getWidth();
        int Height = pnlPrincipal.getHeight();
        p.setSize(width, Height);
    }//GEN-LAST:event_btnProveedores4MouseClicked

    private void btnProveedores4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedores4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedores4MousePressed

    private void btnProveedores5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedores5MouseClicked
        pnlPrincipal.removeAll();
        pnlPrincipal.repaint();
        funcionarios p=new funcionarios();
        pnlPrincipal.add(p).setVisible(true);
        int width = pnlPrincipal.getWidth();
        int Height = pnlPrincipal.getHeight();
        p.setSize(width, Height);
    }//GEN-LAST:event_btnProveedores5MouseClicked

    private void btnProveedores5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedores5MousePressed
      
    }//GEN-LAST:event_btnProveedores5MousePressed

        int x,y;
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new princip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCliente;
    private javax.swing.JPanel btnCompras;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnProducto;
    private javax.swing.JPanel btnProveedores;
    private javax.swing.JPanel btnProveedores1;
    private javax.swing.JPanel btnProveedores2;
    private javax.swing.JPanel btnProveedores3;
    private javax.swing.JPanel btnProveedores4;
    private javax.swing.JPanel btnProveedores5;
    private javax.swing.JPanel btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlMenu;
    public javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel psClientes;
    private javax.swing.JPanel psCompras;
    private javax.swing.JPanel psHome;
    private javax.swing.JPanel psProductos;
    private javax.swing.JPanel psProveedores;
    private javax.swing.JPanel psProveedores1;
    private javax.swing.JPanel psProveedores2;
    private javax.swing.JPanel psProveedores3;
    private javax.swing.JPanel psProveedores4;
    private javax.swing.JPanel psProveedores5;
    private javax.swing.JPanel psProveedores6;
    private javax.swing.JPanel psVentas;
    private javax.swing.JLabel txtHome;
    public javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
